from .baselines.set_to_graph import SetToGraph
from .baselines.set_to_graph_mlp import SetToGraphMLP
from .baselines.set_to_graph_gnn import SetToGraphGNN
from .baselines.set_to_graph_triplets import SetToGraphTri
from .baselines.set_to_graph_siam import SetToGraphSiam
from .baselines.set_partition_mlp import SetPartitionMLP
from .baselines.set_partition_gnn import SetPartitionGNN
from .baselines.triplets_model import SetPartitionTri
from .model import EncoderS2G
